In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [5]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [7]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
float(a[1])

1.0

In [10]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [11]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [12]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [14]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [15]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
points.shape

torch.Size([3, 2])

In [19]:
points = torch.zeros(2,3)
points

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points[0,1]

tensor(1.)

In [22]:
points[0,0]

tensor(4.)

In [23]:
points[0]

tensor([4., 1.])

In [24]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [25]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [26]:
some_list[1:4]

[1, 2, 3]

In [27]:
some_list[1:]

[1, 2, 3, 4, 5]

In [28]:
some_list[:4]

[0, 1, 2, 3]

In [29]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [30]:
some_list[1:4:2]

[1, 3]

In [31]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [33]:
points[1:,0]

tensor([5., 2.])

In [34]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [35]:
points[1:,0]

tensor([5., 2.])

In [36]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [37]:
points.shape

torch.Size([3, 2])

In [38]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [40]:
img_t.shape

torch.Size([3, 5, 5])

In [41]:
batch_t = torch.randn(2,3,5,5)

In [42]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [45]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t*unsqueezed_weights)
batch_weights = (batch_t*unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [47]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [48]:
weights_named = torch.tensor([0.2126, 0.7152,0.0722], names=['channels'])
weights_named

/Users/markun/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:934.)
  """Entry point for launching an IPython kernel.


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [49]:
img_t

tensor([[[ 0.3397,  1.5299,  0.2980,  0.3313,  1.5135],
         [-1.5925,  0.8549,  1.5703, -1.0175, -0.8861],
         [ 1.5723,  0.3540,  1.0624,  0.8524,  0.6153],
         [-0.5731,  1.0705,  0.0392,  0.2977, -0.5551],
         [-0.5826, -0.7421, -0.2266, -0.3026, -0.1010]],

        [[-1.0858, -0.5154, -0.4887,  1.2048,  0.2001],
         [-0.4782, -1.5248, -1.6433,  1.1679, -0.6211],
         [ 0.2623, -0.8833, -0.7616, -0.6230, -0.7247],
         [-0.3008, -0.1751, -1.2138, -1.1210,  0.0477],
         [-0.2626,  0.7354, -0.5942, -1.2688,  0.0860]],

        [[-2.0306,  0.2338, -1.3977,  0.6503,  0.7711],
         [ 1.5080,  0.0341, -0.9174,  0.0484, -0.7458],
         [-0.2232,  1.5732, -0.1983,  1.1870, -0.6521],
         [ 0.5135,  0.5363,  0.1524,  0.3393, -0.0901],
         [-0.1300, -0.7397, -0.2039,  0.6994,  0.2322]]])

In [51]:
img_named = img_t.refine_names(..., 'channels','rows','columns')
batch_named = batch_t.refine_names(...,'channels','rows','columns')
print('img named:',img_named.shape, img_named.names)
print('batch named:',batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [52]:
a = torch.randn(4,5)
a

tensor([[-0.4389, -0.1497,  0.0758, -0.5550,  1.3133],
        [ 0.3933, -0.3059,  0.6193,  0.2898, -0.5771],
        [-0.9728,  0.1571, -0.4112,  0.7686,  0.1907],
        [-1.2027, -0.3357, -0.7733, -0.8791, -1.6446]])

In [63]:
a_named = torch.tensor([0.2126, 0.7152,0.0722], names=['channels'])

In [59]:
a_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [69]:
weights_aligned = weights_named.align_as(img_named)

In [70]:
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [71]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [74]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1,2],[3,4]], dtype=torch.short)
short_points.dtype, double_points.dtype

(torch.int16, torch.float64)

In [75]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()

In [76]:
double_points.dtype

torch.float64

In [77]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10,2).to(dtype=torch.short)

In [78]:
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [79]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [81]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [82]:
points_64

tensor([0.7449, 0.7868, 0.5831, 0.6437, 0.5608], dtype=torch.float64)

In [83]:
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [87]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [89]:
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [90]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [96]:
b = torch.arange(12).reshape(3,4)
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [101]:
b_t = torch.transpose(b,1,0)
b_t

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [102]:
points = torch.tensor([[4.0,1.0],[5.0, 3.0],[2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [103]:
points_storage = points.storage()
points_storage[0]

4.0

In [104]:
points.storage()[1]

1.0

In [105]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [106]:
a = torch.ones(3,2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [107]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [108]:
second_point

tensor([5., 3.])

In [109]:
second_point.size()

torch.Size([2])

In [110]:
second_point.shape

torch.Size([2])

In [111]:
points.stride()

(2, 1)

In [112]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [113]:
second_point.storage_offset()

2

In [114]:
second_point.stride()

(1,)

In [115]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [116]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [117]:
id(points.storage()) == id(points_t.storage())

True

In [118]:
points.stride()

(2, 1)

In [119]:
points_t.stride()

(1, 2)

In [120]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0,2)
some_t.shape

torch.Size([3, 4, 5])

In [121]:
transpose_t.shape

torch.Size([5, 4, 3])

In [122]:
some_t.stride()

(20, 5, 1)

In [123]:
transpose_t.stride()

(1, 5, 20)

In [124]:
points.is_contiguous()

True

In [125]:
points_t.is_contiguous()

False

In [126]:
points = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [127]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [128]:
points_t.stride()

(1, 2)

In [129]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [130]:
points_t_cont.stride()

(3, 1)

In [131]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [133]:
points_gpu = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0, 1.0]], device='cpu')

In [134]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [135]:
points = torch.from_numpy(points_np)

In [136]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [138]:
torch.save(points, '/Users/markun/git/deep-learning-with-pytorch-ja/data/p1ch3/ourpoints.t')

In [140]:
with open('../data/p1ch3/ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [141]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [150]:
a = torch.arange(9)
b = a.view(3,3)

In [151]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [152]:
id(b.storage()) == id(a.storage())

True

In [153]:
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [154]:
c.size()

torch.Size([2, 2])

In [156]:
id(c.storage()) == id(a.storage())

True